Specs/fout meldingen
VNG-Realisatie/Haal-Centraal-BAG-bevragen pull request #397
Opened 2021-04-26 12:07 UTC by MelvLee

2021-04-28 18:13 UTC, JohanBoer requested changes
Voor zover ik kan beoordelen.1 kleine opmerking

2021-04-28 18:13 UTC, JohanBoer commented on features/fout-meldingen.feature
> +    Wil ik gebruikers vriendelijke foutmeldingen
gebruikers vriendelijke --> gebruikersvriendelijke of gebruiksvriendelijke (zoals in de titel)

2021-05-20 08:50 UTC, melsk-r commented on features/fout-meldingen.feature
> +        Als '/adressen/zoek' wordt aangeroepen
Moet dit niet zijn:

Als '/adressen/zoek' wordt aangeroepen zonder de parameter 'zoek'

2021-05-20 08:51 UTC, melsk-r commented on features/fout-meldingen.feature
> +        Als '/adressen?straat=Spui' wordt aangeroepen
Moet niet aangegeven worden dat het hier slechts om een voorbeeld handelt?

2021-05-20 08:58 UTC, melsk-r commented on features/fout-meldingen.feature
> +        Voorbeelden:
Betreft het hier wel voorbeelden. Volgens mij is dit juist de complete lijst met gevallen waar dit voor kan komen.

2021-05-20 09:02 UTC, melsk-r commented on features/fout-meldingen.feature
> +    Abstract Scenario: Er is één of meerdere onbekende resource namen opgegeven
Er **zijn** één of meerdere onbekende resource namen opgegeven

2021-05-20 09:10 UTC, melsk-r commented on features/fout-meldingen.feature
> +        | /adressen              | ?pandIdentificatie=0226100000008856&adresseerbaarObjectIdentificatie=0226010000038820             | Alleen parameter 'pandIdentificatie' of 'adresseerbaarObjectIden
Moet de fout detail niet meer generiek zijn?
Dus:

Alleen parameter 'zoekresultaatidentificatie', 'pandIdentificatie' of 'adresseerbaarObjectIdentificatie' moet zijn opgegeven

2021-05-20 09:11 UTC, melsk-r commented on features/fout-meldingen.feature
> +        | /panden                | ?adresseerbaarObjectIdentificatie=0226010000038820&nummeraanduidingIdentificatie=0226200000038923 | Alleen parameter 'adresseerbaarObjectIdentificatie' of 'nummeraa
Idem

2021-05-20 09:14 UTC, melsk-r commented on features/fout-meldingen.feature
> +    | detail | Geen <resource naam? gevonden met identificatie '<identificatie>' |
Corrigeer in

| detail | Geen <resource naam> gevonden met identificatie '<identificatie>' |

2021-07-13 08:47 UTC, closed without merging